// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEuiaW6tEk6nemATlDJ-v3eJ2fWqpse9o',
    appId: '1:828312716175:web:7ffcaab0b09351450d01fa',
    messagingSenderId: '828312716175',
    projectId: 'hospital-bmi',
    authDomain: 'hospital-bmi.firebaseapp.com',
    databaseURL: 'https://hospital-bmi-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-bmi.appspot.com',
    measurementId: 'G-Q7YCR5LS7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8ENPhFS3_i1gkEUGpGMKCBL0ZTxZQod4',
    appId: '1:828312716175:android:c0a24fe44907cc160d01fa',
    messagingSenderId: '828312716175',
    projectId: 'hospital-bmi',
    databaseURL: 'https://hospital-bmi-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-bmi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7eqfdz7OBMb17p-u_yKmdFS_-O5_8y4Q',
    appId: '1:828312716175:ios:7102aa61f05e84b30d01fa',
    messagingSenderId: '828312716175',
    projectId: 'hospital-bmi',
    databaseURL: 'https://hospital-bmi-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-bmi.appspot.com',
    iosBundleId: 'com.aries.smarthealthcareMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7eqfdz7OBMb17p-u_yKmdFS_-O5_8y4Q',
    appId: '1:828312716175:ios:39214e32329b06970d01fa',
    messagingSenderId: '828312716175',
    projectId: 'hospital-bmi',
    databaseURL: 'https://hospital-bmi-default-rtdb.firebaseio.com',
    storageBucket: 'hospital-bmi.appspot.com',
    iosBundleId: 'com.aries.smarthealthcareMobile.RunnerTests',
  );
}
